# Write your code here :-)
from microbit import *

while True:
    display.set_pixel(0,0,9)
    sleep(250)
    display.clear()
    display.set_pixel(1,1,9)
    sleep(250)
    display.clear()
    display.set_pixel(2,3,9)
    sleep(250)
    display.clear()
    display.set_pixel(3,4,9)
    sleep(250)
    display.clear()
    display.set_pixel(3,4,9)
    sleep(250)
    display.clear()
    display.set_pixel(4,3,9)
    sleep(250)
    display.clear()
    display.set_pixel(4,2,9)
    sleep(250)
    display.clear()
    display.set_pixel(3,1,9)
    sleep(250)
    display.clear()
    display.set_pixel(2,2,9)
    sleep(250)
    display.clear()
    display.set_pixel(2,3,9)
    sleep(250)
    display.clear()
    display.set_pixel(2,4,9)
    sleep(250)
    display.clear()
    display.set_pixel(2,3,9)
    sleep(250)
    display.clear()
    display.set_pixel(2,4,9)
    sleep(250)
    display.clear()
    sleep(1)
